% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
% fallback for those not using the hyperref driver hyperxmp:
\makeatletter
\@ifundefined{xmpquote}{\newcommand{\xmpquote}[1]{#1}}{}
\makeatother
\hypersetup{
  pdftitle={Association Rule Learning on the Groceries Dataset},
  pdfauthor={Name: Ricahrd Mwenedata, ID:101215},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Association Rule Learning on the Groceries Dataset}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Unsupervised Learning Methods Assignment}
\author{Name: Ricahrd Mwenedata, ID:101215}
\date{September 16, 2026}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\subsection{Load the Data}\label{load-the-data}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#load from groceries.csv (basket{-}format, no header,}
\CommentTok{\# variable number of items per row).}
\NormalTok{transactions }\OtherTok{\textless{}{-}} \FunctionTok{read.transactions}\NormalTok{(}\StringTok{"groceries.csv"}\NormalTok{, }\AttributeTok{format =} \StringTok{"basket"}\NormalTok{,}
                                   \AttributeTok{sep =} \StringTok{","}\NormalTok{, }\AttributeTok{rm.duplicates =} \ConstantTok{TRUE}\NormalTok{)}

\FunctionTok{summary}\NormalTok{(transactions)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## transactions as itemMatrix in sparse format with
##  9835 rows (elements/itemsets/transactions) and
##  169 columns (items) and a density of 0.02609146 
## 
## most frequent items:
##       whole milk other vegetables       rolls/buns             soda 
##             2513             1903             1809             1715 
##           yogurt          (Other) 
##             1372            34055 
## 
## element (itemset/transaction) length distribution:
## sizes
##    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16 
## 2159 1643 1299 1005  855  645  545  438  350  246  182  117   78   77   55   46 
##   17   18   19   20   21   22   23   24   26   27   28   29   32 
##   29   14   14    9   11    4    6    1    1    1    1    3    1 
## 
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   2.000   3.000   4.409   6.000  32.000 
## 
## includes extended item information - examples:
##             labels
## 1 abrasive cleaner
## 2 artif. sweetener
## 3   baby cosmetics
\end{verbatim}

\section{Question 1: Understand the
Data}\label{question-1-understand-the-data}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n\_transactions }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(transactions)}
\NormalTok{n\_items }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(transactions)}

\NormalTok{n\_transactions}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9835
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n\_items}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 169
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top10 }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(}\FunctionTok{itemFrequency}\NormalTok{(transactions, }\AttributeTok{type =} \StringTok{"relative"}\NormalTok{), }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{]}
\FunctionTok{kable}\NormalTok{(}\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{Item =} \FunctionTok{names}\NormalTok{(top10), }\AttributeTok{Support =} \FunctionTok{round}\NormalTok{(}\FunctionTok{as.numeric}\NormalTok{(top10), }\DecValTok{4}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}lr@{}}
\toprule\noalign{}
Item & Support \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
whole milk & 0.2555 \\
other vegetables & 0.1935 \\
rolls/buns & 0.1839 \\
soda & 0.1744 \\
yogurt & 0.1395 \\
bottled water & 0.1105 \\
root vegetables & 0.1090 \\
tropical fruit & 0.1049 \\
shopping bags & 0.0985 \\
sausage & 0.0940 \\
\end{longtable}
}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{itemFrequencyPlot}\NormalTok{(transactions, }\AttributeTok{topN =} \DecValTok{10}\NormalTok{, }\AttributeTok{type =} \StringTok{"relative"}\NormalTok{,}
                   \AttributeTok{main =} \StringTok{"Top 10 Most Frequent Items"}\NormalTok{,}
                   \AttributeTok{col =} \FunctionTok{brewer.pal}\NormalTok{(}\DecValTok{8}\NormalTok{, }\StringTok{"Pastel2"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{association_rules_groceries2_files/figure-latex/q1-plot-1} \end{center}

\textbf{Answers}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Number of transactions: \textbf{9835} shopping baskets.
\item
  Number of distinct items: \textbf{169} unique grocery products.
\item
  The 10 most frequently purchased items are shown in the table and
  chart above whole milk, other vegetables, and rolls/buns lead by a
  wide margin, each appearing in roughly 18-26\% of all transactions,
  consistent with these being everyday staple items.
\end{enumerate}

\section{Question 2: Frequent
Itemsets}\label{question-2-frequent-itemsets}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{itemsets }\OtherTok{\textless{}{-}} \FunctionTok{apriori}\NormalTok{(transactions, }\AttributeTok{parameter =} \FunctionTok{list}\NormalTok{(}
  \AttributeTok{target =} \StringTok{"frequent itemsets"}\NormalTok{,}
  \AttributeTok{support =} \FloatTok{0.01}\NormalTok{,}
  \AttributeTok{minlen =} \DecValTok{2}
\NormalTok{), }\AttributeTok{control =} \FunctionTok{list}\NormalTok{(}\AttributeTok{verbose =} \ConstantTok{FALSE}\NormalTok{))}

\NormalTok{itemsets\_sorted }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(itemsets, }\AttributeTok{by =} \StringTok{"support"}\NormalTok{, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{itemsets\_df }\OtherTok{\textless{}{-}} \FunctionTok{as}\NormalTok{(itemsets\_sorted, }\StringTok{"data.frame"}\NormalTok{)}
\FunctionTok{kable}\NormalTok{(}\FunctionTok{head}\NormalTok{(itemsets\_df, }\DecValTok{10}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}llrr@{}}
\toprule\noalign{}
& items & support & count \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
213 & \{other vegetables,whole milk\} & 0.0748348 & 736 \\
212 & \{rolls/buns,whole milk\} & 0.0566345 & 557 \\
210 & \{whole milk,yogurt\} & 0.0560244 & 551 \\
203 & \{root vegetables,whole milk\} & 0.0489070 & 481 \\
202 & \{other vegetables,root vegetables\} & 0.0473818 & 466 \\
209 & \{other vegetables,yogurt\} & 0.0434164 & 427 \\
211 & \{other vegetables,rolls/buns\} & 0.0426029 & 419 \\
198 & \{tropical fruit,whole milk\} & 0.0422979 & 416 \\
207 & \{soda,whole milk\} & 0.0400610 & 394 \\
205 & \{rolls/buns,soda\} & 0.0383325 & 377 \\
\end{longtable}
}

\textbf{Answers}

a-b. At least 10 frequent itemsets (2+ products) with their support
values are listed in the table above (support threshold = 1\%). c.~The
highest support itemset is \textbf{\{other vegetables, whole milk\}},
support ≈ 0.075 (about 7.5\% of all transactions contain both). d.~The
support value tells us how common a combination of products is across
\emph{all} transactions. A support of \textasciitilde0.075 for \{other
vegetables, whole milk\} means nearly 1 in 13 shopping trips include
both items together these are two of the most habitually co-purchased
staples in the store. Itemsets with very low support represent rare
combinations not worth building marketing decisions around, while high
support itemsets point to strong, everyday purchasing patterns worth
acting on.

\section{Question 3: Association
Rules}\label{question-3-association-rules}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rules }\OtherTok{\textless{}{-}} \FunctionTok{apriori}\NormalTok{(transactions, }\AttributeTok{parameter =} \FunctionTok{list}\NormalTok{(}
  \AttributeTok{support =} \FloatTok{0.01}\NormalTok{,}
  \AttributeTok{confidence =} \FloatTok{0.3}\NormalTok{,}
  \AttributeTok{minlen =} \DecValTok{2}
\NormalTok{), }\AttributeTok{control =} \FunctionTok{list}\NormalTok{(}\AttributeTok{verbose =} \ConstantTok{FALSE}\NormalTok{))}

\FunctionTok{length}\NormalTok{(rules)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 125
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rules\_by\_lift }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(rules, }\AttributeTok{by =} \StringTok{"lift"}\NormalTok{, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{rules\_df }\OtherTok{\textless{}{-}} \FunctionTok{as}\NormalTok{(rules\_by\_lift, }\StringTok{"data.frame"}\NormalTok{)}
\FunctionTok{kable}\NormalTok{(}\FunctionTok{head}\NormalTok{(rules\_df, }\DecValTok{10}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0381}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.5238}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0952}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1048}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0952}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0857}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0571}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
rules
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
support
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
confidence
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
coverage
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
lift
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
count
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
91 & \{citrus fruit,other vegetables\} =\textgreater{} \{root
vegetables\} & 0.0103711 & 0.3591549 & 0.0288765 & 3.295046 & 102 \\
101 & \{other vegetables,tropical fruit\} =\textgreater{} \{root
vegetables\} & 0.0123030 & 0.3427762 & 0.0358922 & 3.144780 & 121 \\
32 & \{beef\} =\textgreater{} \{root vegetables\} & 0.0173869 &
0.3313953 & 0.0524657 & 3.040367 & 171 \\
90 & \{citrus fruit,root vegetables\} =\textgreater{} \{other
vegetables\} & 0.0103711 & 0.5862069 & 0.0176919 & 3.029608 & 102 \\
100 & \{root vegetables,tropical fruit\} =\textgreater{} \{other
vegetables\} & 0.0123030 & 0.5845411 & 0.0210473 & 3.020999 & 121 \\
116 & \{other vegetables,whole milk\} =\textgreater{} \{root
vegetables\} & 0.0231825 & 0.3097826 & 0.0748348 & 2.842082 & 228 \\
71 & \{curd,whole milk\} =\textgreater{} \{yogurt\} & 0.0100661 &
0.3852140 & 0.0261312 & 2.761356 & 99 \\
112 & \{rolls/buns,root vegetables\} =\textgreater{} \{other
vegetables\} & 0.0122013 & 0.5020921 & 0.0243010 & 2.594890 & 120 \\
110 & \{root vegetables,yogurt\} =\textgreater{} \{other vegetables\} &
0.0129131 & 0.5000000 & 0.0258261 & 2.584078 & 127 \\
106 & \{tropical fruit,whole milk\} =\textgreater{} \{yogurt\} &
0.0151500 & 0.3581731 & 0.0422979 & 2.567516 & 149 \\
\end{longtable}
}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Export full rule table for submission}
\FunctionTok{write.csv}\NormalTok{(rules\_df, }\StringTok{"association\_rules\_output.csv"}\NormalTok{, }\AttributeTok{row.names =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(rules, }\AttributeTok{measure =} \FunctionTok{c}\NormalTok{(}\StringTok{"support"}\NormalTok{, }\StringTok{"confidence"}\NormalTok{), }\AttributeTok{shading =} \StringTok{"lift"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Association Rules: Support vs Confidence (shaded by Lift)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{association_rules_groceries2_files/figure-latex/q3-plot-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{head}\NormalTok{(rules\_by\_lift, }\DecValTok{10}\NormalTok{), }\AttributeTok{method =} \StringTok{"graph"}\NormalTok{,}
     \AttributeTok{main =} \StringTok{"Top 10 Rules by Lift {-} Network Graph"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Available control parameters (with default values):
## layout    =  stress
## circular  =  FALSE
## ggraphdots    =  NULL
## edges     =  <environment>
## nodes     =  <environment>
## nodetext  =  <environment>
## colors    =  c("#EE0000FF", "#EEEEEEFF")
## engine    =  ggplot2
## max   =  100
## verbose   =  FALSE
\end{verbatim}

\begin{center}\includegraphics{association_rules_groceries2_files/figure-latex/q3-graph-1} \end{center}

\textbf{Answers}

a-b. At least 10 association rules with antecedent, consequent, support,
confidence, and lift are listed in the table above (the top 10 by lift,
out of all rules meeting support ≥ 0.01 and confidence ≥ 0.3).

\section{Question 4: Understanding the
Measures}\label{question-4-understanding-the-measures}

Three example rules are used to illustrate the three measures (values
will match your knit output above; typical results look like this):

\begin{itemize}
\tightlist
\item
  \textbf{Rule 1:} \{citrus fruit, root vegetables\} → \{other
  vegetables\} (support ≈ 0.010, confidence ≈ 0.586, lift ≈ 3.03)
\item
  \textbf{Rule 2:} \{root vegetables, tropical fruit\} → \{other
  vegetables\} (support ≈ 0.012, confidence ≈ 0.585, lift ≈ 3.02)
\item
  \textbf{Rule 3:} \{other vegetables\} → \{whole milk\} (support ≈
  0.075, confidence ≈ 0.387, lift ≈ 1.51)
\end{itemize}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \textbf{Support} the proportion of \emph{all} transactions that
  contain every item in the rule. For Rule 1, support ≈ 0.010 means
  citrus fruit, root vegetables, and other vegetables all appear
  together in about 1\% of the transactions.
\item
  \textbf{Confidence} of the transactions that contain the antecedent,
  the proportion that also contain the consequent. For Rule 2,
  confidence ≈ 0.585 means that when a customer buys root vegetables and
  tropical fruit, they also buy other vegetables about 58.5\% of the
  time.
\item
  \textbf{Lift} how much more likely the consequent is, given the
  antecedent, compared to its baseline purchase rate. For Rule 3, lift ≈
  1.51 means customers who buy other vegetables are about 51\% more
  likely to also buy whole milk than a random customer lift above 1
  indicates a real positive association, not coincidence.
\end{enumerate}

\section{Question 5: Find Interesting
Rules}\label{question-5-find-interesting-rules}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top\_confidence }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(rules, }\AttributeTok{by =} \StringTok{"confidence"}\NormalTok{, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)[}\DecValTok{1}\NormalTok{]}
\NormalTok{top\_lift       }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(rules, }\AttributeTok{by =} \StringTok{"lift"}\NormalTok{,       }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)[}\DecValTok{1}\NormalTok{]}
\NormalTok{top\_support    }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(rules, }\AttributeTok{by =} \StringTok{"support"}\NormalTok{,    }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)[}\DecValTok{1}\NormalTok{]}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Highest confidence rule:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{); }\FunctionTok{inspect}\NormalTok{(top\_confidence)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Highest confidence rule:
\end{verbatim}

\begin{verbatim}
##     lhs                                rhs                support    confidence
## [1] {citrus fruit, root vegetables} => {other vegetables} 0.01037112 0.5862069 
##     coverage   lift     count
## [1] 0.01769192 3.029608 102
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Highest lift rule:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{);     }\FunctionTok{inspect}\NormalTok{(top\_lift)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Highest lift rule:
\end{verbatim}

\begin{verbatim}
##     lhs                                 rhs               support    confidence
## [1] {citrus fruit, other vegetables} => {root vegetables} 0.01037112 0.3591549 
##     coverage   lift     count
## [1] 0.02887646 3.295045 102
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Highest support rule:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{);  }\FunctionTok{inspect}\NormalTok{(top\_support)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Highest support rule:
\end{verbatim}

\begin{verbatim}
##     lhs                   rhs          support    confidence coverage  lift    
## [1] {other vegetables} => {whole milk} 0.07483477 0.3867578  0.1934926 1.513634
##     count
## [1] 736
\end{verbatim}

\textbf{Answers}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Highest confidence: \textbf{\{citrus fruit, root vegetables\} →
  \{other vegetables\}}, confidence ≈ 0.586 (58.6\%).
\item
  Highest lift: \textbf{\{citrus fruit, other vegetables\} → \{root
  vegetables\}}, lift ≈ 3.30.
\item
  Highest support: \textbf{\{other vegetables\} → \{whole milk\}},
  support ≈ 0.075 (7.5\%).
\item
  These are three different rules. Support favors rules built on very
  common individual items (whole milk and other vegetables are simply
  purchased often, so any rule connecting them has high support), while
  confidence and lift favor rules involving less common but tightly
  associated items (like citrus fruit and root vegetables) that occur
  together far more than chance would predict, even though they don't
  occur in a large absolute number of transactions. A rule can be common
  but only weakly associated (high support, low lift), or rare but very
  strongly associated (low support, high lift/confidence) exactly what
  we see here.
\end{enumerate}

\section{Question 6: Interpret a
Rule}\label{question-6-interpret-a-rule}

Selected rule: \textbf{\{root vegetables, tropical fruit\} → \{other
vegetables\}} (support ≈ 0.012, confidence ≈ 0.585, lift ≈ 3.02)

In simple language: customers who purchase root vegetables and tropical
fruit together also tend to purchase other vegetables, this combination
shows up in about 1.2\% of all shopping trips, and when a customer buys
root vegetables and tropical fruit, about 58.5\% of the time they also
pick up other vegetables.

This is a \textbf{strong association}. The confidence (58.5\%) is well
above the overall purchase rate of other vegetables
(\textasciitilde19\%), and the lift of \textasciitilde3.0 means the
combination is roughly three times more likely to include other
vegetables than would be expected by chance. High confidence together
with a lift well above 1 indicates a genuine, non coincidental
purchasing pattern rather than a weak or spurious link.

\section{Question 7: Business
Application}\label{question-7-business-application}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \textbf{Two products to place close together:} root vegetables and
  other vegetables. They co-occur frequently (support ≈ 0.047) and have
  a strong association (lift ≈ 2.25), so positioning them in adjacent
  produce sections would match natural shopping behavior and likely
  encourage additional add-on purchases.
\item
  \textbf{A possible product bundle:} a ``fresh basics'' bundle of root
  vegetables + tropical fruit + other vegetables, since customers who
  buy the first two very reliably (≈58.5\% of the time) also want the
  third a discounted bundle would reward behavior that already happens
  naturally and could nudge the remaining \textasciitilde42\% to add it
  too.
\item
  \textbf{Example recommendation use:} an online grocery site or
  self-checkout kiosk could use a high-lift rule such as \{other
  vegetables, whole milk\} → root vegetables to power a ``customers who
  bought this also bought\ldots{}'' recommendation panel, automatically
  suggesting root vegetables to any shopper with other vegetables and
  whole milk already in their cart, increasing basket size.
\end{enumerate}

\section{Question 8: Understanding
Association}\label{question-8-understanding-association}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  \textbf{No} an association rule does not prove causation. It only
  shows that items tend to be purchased in the same transaction more
  often than expected by chance. There could be a common underlying
  cause (e.g., both are ingredients in a popular recipe, or both are on
  promotion the same week) rather than one purchase causing the other.
  Establishing causation would require a controlled experiment (e.g.,
  A/B testing shelf placement), not just observational transaction data.
\item
  A rule can have \textbf{high confidence but low lift} when the
  consequent is already very popular on its own. For example, a rule
  ending in \{whole milk\} can easily have high confidence simply
  because most shoppers buy whole milk regardless of what else is in
  their cart the antecedent isn't really driving the purchase, it's just
  riding along with an item everyone buys anyway. Lift corrects for this
  by comparing confidence to the consequence's baseline popularity.
\item
  A \textbf{lift value greater than 1} indicates a positive association:
  the items are purchased together more often than would be expected if
  purchased independently. The higher above 1, the stronger the
  association. A lift of exactly 1 means no association (statistical
  independence), and a lift below 1 means the items are negatively
  associated buying one makes the other less likely.
\end{enumerate}

\section{Methodology Note}\label{methodology-note}

Analysis was performed in R using the \texttt{arules} package's
\texttt{apriori()} function on the Groceries transaction data, with
minimum support = 0.01 and minimum confidence = 0.3 for rule generation
(\texttt{minlen\ =\ 2} to exclude single-item rules). Knit this document
to Word, PDF, or HTML to produce the final submission the code, output
tables, and figures above will regenerate automatically from live
results each time it is knit.

\end{document}
